//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DancingGoat {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DancingGoat() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DancingGoat.App_Data.DancingGoat", typeof(DancingGoat).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Address_City {
            get {
                return ResourceManager.GetString("Address.City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Address_Country {
            get {
                return ResourceManager.GetString("Address.Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Country field is required.
        /// </summary>
        public static string Address_CountryIsRequired {
            get {
                return ResourceManager.GetString("Address.CountryIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line.
        /// </summary>
        public static string Address_Line1 {
            get {
                return ResourceManager.GetString("Address.Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. street address, P.O.box, c/o.
        /// </summary>
        public static string Address_Line1Explanation {
            get {
                return ResourceManager.GetString("Address.Line1Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line 2.
        /// </summary>
        public static string Address_Line2 {
            get {
                return ResourceManager.GetString("Address.Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. apartment, suite, unit, building.
        /// </summary>
        public static string Address_Line2Explanation {
            get {
                return ResourceManager.GetString("Address.Line2Explanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (new).
        /// </summary>
        public static string Address_NewAddress {
            get {
                return ResourceManager.GetString("Address.NewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select country.
        /// </summary>
        public static string Address_SelectCountry {
            get {
                return ResourceManager.GetString("Address.SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select state.
        /// </summary>
        public static string Address_SelectState {
            get {
                return ResourceManager.GetString("Address.SelectState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string Address_State {
            get {
                return ResourceManager.GetString("Address.State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The State field is required.
        /// </summary>
        public static string Address_StateIsRequired {
            get {
                return ResourceManager.GetString("Address.StateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        public static string Address_Zip {
            get {
                return ResourceManager.GetString("Address.Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest article.
        /// </summary>
        public static string Articles_LatestOne {
            get {
                return ResourceManager.GetString("Articles.LatestOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More articles.
        /// </summary>
        public static string Articles_More {
            get {
                return ResourceManager.GetString("Articles.More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related articles.
        /// </summary>
        public static string Articles_RelatedArticles {
            get {
                return ResourceManager.GetString("Articles.RelatedArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roasting premium coffee.
        /// </summary>
        public static string Banner_Default_Heading {
            get {
                return ResourceManager.GetString("Banner.Default.Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover the fascinating world of Dancing Goat high-quality coffee and you will never miss a single coffee break again..
        /// </summary>
        public static string Banner_Default_Text {
            get {
                return ResourceManager.GetString("Banner.Default.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombia in store.
        /// </summary>
        public static string Banner_Martina_Heading {
            get {
                return ResourceManager.GetString("Banner.Martina.Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sweet and full bodied thanks to hard work, family traditions and favorable climate conditions. Perfect as is, that&apos;s Colombian coffee..
        /// </summary>
        public static string Banner_Martina_Text {
            get {
                return ResourceManager.GetString("Banner.Martina.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee machine rental.
        /// </summary>
        public static string Banner_Tony_Heading {
            get {
                return ResourceManager.GetString("Banner.Tony.Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Premium coffee deserves premium process. Take advantage of your partnership and rent one of our professional coffee machines..
        /// </summary>
        public static string Banner_Tony_Text {
            get {
                return ResourceManager.GetString("Banner.Tony.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dishwasher safe.
        /// </summary>
        public static string Brewer_IsDishwasherSafe {
            get {
                return ResourceManager.GetString("Brewer.IsDishwasherSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brewers.
        /// </summary>
        public static string Brewers {
            get {
                return ResourceManager.GetString("Brewers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aerobie.
        /// </summary>
        public static string Brewers_Aerobie {
            get {
                return ResourceManager.GetString("Brewers.Aerobie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string Brewers_Availability {
            get {
                return ResourceManager.GetString("Brewers.Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemex.
        /// </summary>
        public static string Brewers_Chemex {
            get {
                return ResourceManager.GetString("Brewers.Chemex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espro.
        /// </summary>
        public static string Brewers_Espro {
            get {
                return ResourceManager.GetString("Brewers.Espro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hario.
        /// </summary>
        public static string Brewers_Hario {
            get {
                return ResourceManager.GetString("Brewers.Hario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Brewers_Manufacturers {
            get {
                return ResourceManager.GetString("Brewers.Manufacturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching products..
        /// </summary>
        public static string Brewers_NoMatchingProducts {
            get {
                return ResourceManager.GetString("Brewers.NoMatchingProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only in stock.
        /// </summary>
        public static string Brewers_OnlyInStock {
            get {
                return ResourceManager.GetString("Brewers.OnlyInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Brewers_Price {
            get {
                return ResourceManager.GetString("Brewers.Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Brewers_PublicStatus {
            get {
                return ResourceManager.GetString("Brewers.PublicStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cafes.
        /// </summary>
        public static string Cafes {
            get {
                return ResourceManager.GetString("Cafes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find the nearest cafe.
        /// </summary>
        public static string Cafes_MapTitle {
            get {
                return ResourceManager.GetString("Cafes.MapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find out more.
        /// </summary>
        public static string Cafes_More {
            get {
                return ResourceManager.GetString("Cafes.More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to checkout.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back to Billing &amp; Delivery.
        /// </summary>
        public static string Checkout_BackToCustomerDetails {
            get {
                return ResourceManager.GetString("Checkout.BackToCustomerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back to shopping cart.
        /// </summary>
        public static string Checkout_BackToShoppingCart {
            get {
                return ResourceManager.GetString("Checkout.BackToShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing address.
        /// </summary>
        public static string Checkout_BillingAddress {
            get {
                return ResourceManager.GetString("Checkout.BillingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing details.
        /// </summary>
        public static string Checkout_BillingDetails {
            get {
                return ResourceManager.GetString("Checkout.BillingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm and pay.
        /// </summary>
        public static string Checkout_ConfirmAndPayButton {
            get {
                return ResourceManager.GetString("Checkout.ConfirmAndPayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continue shopping.
        /// </summary>
        public static string Checkout_ContinueShopping {
            get {
                return ResourceManager.GetString("Checkout.ContinueShopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount coupon.
        /// </summary>
        public static string Checkout_CouponCode {
            get {
                return ResourceManager.GetString("Checkout.CouponCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount coupon has been applied..
        /// </summary>
        public static string Checkout_CouponCodeApplied {
            get {
                return ResourceManager.GetString("Checkout.CouponCodeApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer details.
        /// </summary>
        public static string Checkout_CustomerDetails {
            get {
                return ResourceManager.GetString("Checkout.CustomerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery options.
        /// </summary>
        public static string Checkout_DeliveryOptions {
            get {
                return ResourceManager.GetString("Checkout.DeliveryOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add some item to your shopping cart..
        /// </summary>
        public static string Checkout_EmptyCartError {
            get {
                return ResourceManager.GetString("Checkout.EmptyCartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill in your billing details and delivery preferences and proceed to review your order..
        /// </summary>
        public static string Checkout_FillDetailsAndProceed {
            get {
                return ResourceManager.GetString("Checkout.FillDetailsAndProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon code is not valid..
        /// </summary>
        public static string Checkout_InvalidCouponCode {
            get {
                return ResourceManager.GetString("Checkout.InvalidCouponCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered items.
        /// </summary>
        public static string Checkout_OrderedItems {
            get {
                return ResourceManager.GetString("Checkout.OrderedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order cannot be completed.
        /// </summary>
        public static string Checkout_OrderFailed {
            get {
                return ResourceManager.GetString("Checkout.OrderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review your shopping cart and checkout.
        /// </summary>
        public static string Checkout_ReviewAndCheckout {
            get {
                return ResourceManager.GetString("Checkout.ReviewAndCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to review order.
        /// </summary>
        public static string Checkout_ReviewOrder {
            get {
                return ResourceManager.GetString("Checkout.ReviewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review your shopping cart and checkout.
        /// </summary>
        public static string Checkout_ReviewShoppingCart {
            get {
                return ResourceManager.GetString("Checkout.ReviewShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping details.
        /// </summary>
        public static string Checkout_ShippingDetails {
            get {
                return ResourceManager.GetString("Checkout.ShippingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping cart is empty.
        /// </summary>
        public static string Checkout_ShoppingCartIsEmpty {
            get {
                return ResourceManager.GetString("Checkout.ShoppingCartIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Checkout_ShoppingCartPreview {
            get {
                return ResourceManager.GetString("Checkout.ShoppingCartPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You!.
        /// </summary>
        public static string Checkout_ThankYou {
            get {
                return ResourceManager.GetString("Checkout.ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your shopping cart.
        /// </summary>
        public static string Checkout_YourShoppingCart {
            get {
                return ResourceManager.GetString("Checkout.YourShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        public static string Coffee_Altitude {
            get {
                return ResourceManager.GetString("Coffee.Altitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm.
        /// </summary>
        public static string Coffee_Farm {
            get {
                return ResourceManager.GetString("Coffee.Farm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decaf.
        /// </summary>
        public static string Coffee_IsDecaf {
            get {
                return ResourceManager.GetString("Coffee.IsDecaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Coffee_Processing {
            get {
                return ResourceManager.GetString("Coffee.Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variety.
        /// </summary>
        public static string Coffee_Variety {
            get {
                return ResourceManager.GetString("Coffee.Variety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffees.
        /// </summary>
        public static string Coffees {
            get {
                return ResourceManager.GetString("Coffees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caffeine.
        /// </summary>
        public static string Coffees_Caffeine {
            get {
                return ResourceManager.GetString("Coffees.Caffeine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coffee processing.
        /// </summary>
        public static string Coffees_CoffeeProcessing {
            get {
                return ResourceManager.GetString("Coffees.CoffeeProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural.
        /// </summary>
        public static string Coffees_Natural {
            get {
                return ResourceManager.GetString("Coffees.Natural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching products..
        /// </summary>
        public static string Coffees_NoMatchingProducts {
            get {
                return ResourceManager.GetString("Coffees.NoMatchingProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decaf.
        /// </summary>
        public static string Coffees_OnlyDecaf {
            get {
                return ResourceManager.GetString("Coffees.OnlyDecaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-washed.
        /// </summary>
        public static string Coffees_Semiwashed {
            get {
                return ResourceManager.GetString("Coffees.Semiwashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Washed.
        /// </summary>
        public static string Coffees_Washed {
            get {
                return ResourceManager.GetString("Coffees.Washed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our cafes.
        /// </summary>
        public static string CompanyCafes {
            get {
                return ResourceManager.GetString("CompanyCafes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taste Our Coffee.
        /// </summary>
        public static string CompanyCafes_Title {
            get {
                return ResourceManager.GetString("CompanyCafes.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact_Title {
            get {
                return ResourceManager.GetString("Contact.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error sending message.
        /// </summary>
        public static string ContactUs_ErrorSending {
            get {
                return ResourceManager.GetString("ContactUs.ErrorSending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. Please go to {0} page and try again later..
        /// </summary>
        public static string ContactUs_ErrorText {
            get {
                return ResourceManager.GetString("ContactUs.ErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop in.
        /// </summary>
        public static string ContactUs_MapTitle {
            get {
                return ResourceManager.GetString("ContactUs.MapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks! We&apos;ll get back to you soon..
        /// </summary>
        public static string ContactUs_Thanks {
            get {
                return ResourceManager.GetString("ContactUs.Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send us a message.
        /// </summary>
        public static string ContactUs_Title {
            get {
                return ResourceManager.GetString("ContactUs.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string DanicngGoatMvc_UserName {
            get {
                return ResourceManager.GetString("DanicngGoatMvc.UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in to access your billing and delivery details.
        /// </summary>
        public static string DeliveryDetails_AccessDetails {
            get {
                return ResourceManager.GetString("DeliveryDetails.AccessDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already a customer?.
        /// </summary>
        public static string DeliveryDetails_AlreadyCustomer {
            get {
                return ResourceManager.GetString("DeliveryDetails.AlreadyCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string DeliveryDetails_SignIn {
            get {
                return ResourceManager.GetString("DeliveryDetails.SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us.
        /// </summary>
        public static string FollowUs_Title {
            get {
                return ResourceManager.GetString("FollowUs.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us on Facebook.
        /// </summary>
        public static string FollowUsOnFacebook {
            get {
                return ResourceManager.GetString("FollowUsOnFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us on Twitter.
        /// </summary>
        public static string FollowUsOnTwitter {
            get {
                return ResourceManager.GetString("FollowUsOnTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password.
        /// </summary>
        public static string ForgottenPassword {
            get {
                return ResourceManager.GetString("ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address.
        /// </summary>
        public static string General_InvalidEmail {
            get {
                return ResourceManager.GetString("General.InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum allowed length of the input text is {1}.
        /// </summary>
        public static string General_MaximumInputLengthExceeded {
            get {
                return ResourceManager.GetString("General.MaximumInputLengthExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string General_No {
            get {
                return ResourceManager.GetString("General.No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string General_Submit {
            get {
                return ResourceManager.GetString("General.Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string General_Yes {
            get {
                return ResourceManager.GetString("General.Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscriber has been already subscribed..
        /// </summary>
        public static string News_AlreadySubscribed {
            get {
                return ResourceManager.GetString("News.AlreadySubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A confirmation link has been sent to your email..
        /// </summary>
        public static string News_ConfirmationSent {
            get {
                return ResourceManager.GetString("News.ConfirmationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already subscribed..
        /// </summary>
        public static string News_ConfirmSubscriptionAlreadyConfirmed {
            get {
                return ResourceManager.GetString("News.ConfirmSubscriptionAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription confirmation error.
        /// </summary>
        public static string News_ConfirmSubscriptionError {
            get {
                return ResourceManager.GetString("News.ConfirmSubscriptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subscription confirmation has failed. Please try again later..
        /// </summary>
        public static string News_ConfirmSubscriptionFailed {
            get {
                return ResourceManager.GetString("News.ConfirmSubscriptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation link is not valid..
        /// </summary>
        public static string News_ConfirmSubscriptionInvalidDateTime {
            get {
                return ResourceManager.GetString("News.ConfirmSubscriptionInvalidDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation link is not valid..
        /// </summary>
        public static string News_ConfirmSubscriptionInvalidLink {
            get {
                return ResourceManager.GetString("News.ConfirmSubscriptionInvalidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription confirmed.
        /// </summary>
        public static string News_ConfirmSubscriptionOK {
            get {
                return ResourceManager.GetString("News.ConfirmSubscriptionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subscription has been confirmed..
        /// </summary>
        public static string News_ConfirmSubscriptionSucceeded {
            get {
                return ResourceManager.GetString("News.ConfirmSubscriptionSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subscription confirmation link has expired. Please subscribe again..
        /// </summary>
        public static string News_ConfirmSubscriptionTimeExceeded {
            get {
                return ResourceManager.GetString("News.ConfirmSubscriptionTimeExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You weren&apos;t unsubscribed because your unsubscription link is not valid..
        /// </summary>
        public static string News_InvalidUnsubscriptionLink {
            get {
                return ResourceManager.GetString("News.InvalidUnsubscriptionLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum length of email address is {1} characters..
        /// </summary>
        public static string News_LongEmail {
            get {
                return ResourceManager.GetString("News.LongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string News_Subscribe {
            get {
                return ResourceManager.GetString("News.Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been subscribed.
        /// </summary>
        public static string News_Subscribed {
            get {
                return ResourceManager.GetString("News.Subscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during subscribing. Please try again..
        /// </summary>
        public static string News_SubscribeError {
            get {
                return ResourceManager.GetString("News.SubscribeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to stay up to date? Please leave us your email address..
        /// </summary>
        public static string News_SubscriberEmail {
            get {
                return ResourceManager.GetString("News.SubscriberEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter subscription.
        /// </summary>
        public static string News_Subscription {
            get {
                return ResourceManager.GetString("News.Subscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News &amp; Updates.
        /// </summary>
        public static string News_Title {
            get {
                return ResourceManager.GetString("News.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We would like to offer you a coffee to go, but we can&apos;t, because we have just removed your email from the list..
        /// </summary>
        public static string News_Unsubscribed {
            get {
                return ResourceManager.GetString("News.Unsubscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been unsubscribed from all email marketing campaigns..
        /// </summary>
        public static string News_UnsubscribedAll {
            get {
                return ResourceManager.GetString("News.UnsubscribedAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!.
        /// </summary>
        public static string News_UnsubscribeError {
            get {
                return ResourceManager.GetString("News.UnsubscribeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goodbye!.
        /// </summary>
        public static string News_UnsubscribeOK {
            get {
                return ResourceManager.GetString("News.UnsubscribeOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter unsubscription.
        /// </summary>
        public static string News_Unsubscribtion {
            get {
                return ResourceManager.GetString("News.Unsubscribtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact us.
        /// </summary>
        public static string NotFound_ContactUs {
            get {
                return ResourceManager.GetString("NotFound.ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to homepage.
        /// </summary>
        public static string NotFound_GoHome {
            get {
                return ResourceManager.GetString("NotFound.GoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to homepage.
        /// </summary>
        public static string NotFound_Homepage {
            get {
                return ResourceManager.GetString("NotFound.Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head back to {0} using the navigation, use search or {1}..
        /// </summary>
        public static string NotFound_Instructions {
            get {
                return ResourceManager.GetString("NotFound.Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are really sorry, something has gone wrong. It seems that page you requested doesn&apos;t exist..
        /// </summary>
        public static string NotFound_Message {
            get {
                return ResourceManager.GetString("NotFound.Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! Page not found....
        /// </summary>
        public static string NotFound_Title {
            get {
                return ResourceManager.GetString("NotFound.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions or suggestions regarding the order process, call us at {0}..
        /// </summary>
        public static string Order_Questions {
            get {
                return ResourceManager.GetString("Order.Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your order was successfully processed. We will pack your items carefully and ship them to you right away..
        /// </summary>
        public static string Order_Success {
            get {
                return ResourceManager.GetString("Order.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other places where you can drink our coffee.
        /// </summary>
        public static string PartnerCafes_Title {
            get {
                return ResourceManager.GetString("PartnerCafes.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnership.
        /// </summary>
        public static string Partnership {
            get {
                return ResourceManager.GetString("Partnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your business is also our business. Become a part of our brand and benefit from it..
        /// </summary>
        public static string Partnership_ApplicationText {
            get {
                return ResourceManager.GetString("Partnership.ApplicationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnership Application.
        /// </summary>
        public static string Partnership_ApplicationTitle {
            get {
                return ResourceManager.GetString("Partnership.ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLY.
        /// </summary>
        public static string Partnership_Form_Apply {
            get {
                return ResourceManager.GetString("Partnership.Form.Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string Partnership_Form_CompanyName {
            get {
                return ResourceManager.GetString("Partnership.Form.CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Partnership_Form_Email {
            get {
                return ResourceManager.GetString("Partnership.Form.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Partnership_Form_FirstName {
            get {
                return ResourceManager.GetString("Partnership.Form.FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am interested in....
        /// </summary>
        public static string Partnership_Form_Interest {
            get {
                return ResourceManager.GetString("Partnership.Form.Interest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Becoming a partner café.
        /// </summary>
        public static string Partnership_Form_Interest_PartnerCafe {
            get {
                return ResourceManager.GetString("Partnership.Form.Interest.PartnerCafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Becoming a wholesale partner.
        /// </summary>
        public static string Partnership_Form_Interest_WholesalePartner {
            get {
                return ResourceManager.GetString("Partnership.Form.Interest.WholesalePartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Partnership_Form_LastName {
            get {
                return ResourceManager.GetString("Partnership.Form.LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Partnership_Form_Phone {
            get {
                return ResourceManager.GetString("Partnership.Form.Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple sale levels of up to 25% based on the quarterly quota.
        /// </summary>
        public static string Partnership_LeftInfoItem1 {
            get {
                return ResourceManager.GetString("Partnership.LeftInfoItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free tableware and merchandise.
        /// </summary>
        public static string Partnership_LeftInfoItem2 {
            get {
                return ResourceManager.GetString("Partnership.LeftInfoItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotional materials.
        /// </summary>
        public static string Partnership_LeftInfoItem3 {
            get {
                return ResourceManager.GetString("Partnership.LeftInfoItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wholesale Partner Program.
        /// </summary>
        public static string Partnership_LeftInfoTitle {
            get {
                return ResourceManager.GetString("Partnership.LeftInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ll contact you within 48 hours to discuss details and explain any question of yours regarding the partnership..
        /// </summary>
        public static string Partnership_RequestLabel {
            get {
                return ResourceManager.GetString("Partnership.RequestLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for café owners only.
        /// </summary>
        public static string Partnership_RightInfoItem1 {
            get {
                return ResourceManager.GetString("Partnership.RightInfoItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple sale levels of up to 25% based on the quarterly quota.
        /// </summary>
        public static string Partnership_RightInfoItem2 {
            get {
                return ResourceManager.GetString("Partnership.RightInfoItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional coffee machine rental and leasing.
        /// </summary>
        public static string Partnership_RightInfoItem3 {
            get {
                return ResourceManager.GetString("Partnership.RightInfoItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion by Dancing Goat.
        /// </summary>
        public static string Partnership_RightInfoItem4 {
            get {
                return ResourceManager.GetString("Partnership.RightInfoItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barista, promotion, and management training.
        /// </summary>
        public static string Partnership_RightInfoItem5 {
            get {
                return ResourceManager.GetString("Partnership.RightInfoItem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special merchandise and access to limited editions.
        /// </summary>
        public static string Partnership_RightInfoItem6 {
            get {
                return ResourceManager.GetString("Partnership.RightInfoItem6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Café Program.
        /// </summary>
        public static string Partnership_RightInfoTitle {
            get {
                return ResourceManager.GetString("Partnership.RightInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your company buys in our on-line store regularly, we&apos;d like to reward you and offer you our wholesale partner program. Register on the form below and we&apos;ll contact you within two days with a newly created business account with which you can buy discounted products. The discount is of up to 25% and is settled on a quarterly basis according to your purchases the quarter before. Besides that, you get free tableware and merchandise along with other promotional materials.&lt;/br&gt;&lt;/br&gt;
        ///
        ///If you have a café or yo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Partnership_Text {
            get {
                return ResourceManager.GetString("Partnership.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does it work?.
        /// </summary>
        public static string Partnership_Title {
            get {
                return ResourceManager.GetString("Partnership.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string PasswordReset {
            get {
                return ResourceManager.GetString("PasswordReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the email address associated with your account to reset your password.
        /// </summary>
        public static string PasswordReset_Description {
            get {
                return ResourceManager.GetString("PasswordReset.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string PasswordReset_Email {
            get {
                return ResourceManager.GetString("PasswordReset.Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have submitted a request to change your password. Please click &lt;a href=&quot;{0}&quot;&gt;this link&lt;/a&gt; to set a new password.&lt;br/&gt;&lt;br/&gt; 
        ///If you did not submit the request please let us know..
        /// </summary>
        public static string PasswordReset_Email_Body {
            get {
                return ResourceManager.GetString("PasswordReset.Email.Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email.
        /// </summary>
        public static string PasswordReset_Email_Empty {
            get {
                return ResourceManager.GetString("PasswordReset.Email.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for changing your password.
        /// </summary>
        public static string PasswordReset_Email_Subject {
            get {
                return ResourceManager.GetString("PasswordReset.Email.Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the email address is known to us, we&apos;ll send a password recovery link in a few minutes..
        /// </summary>
        public static string PasswordReset_EmailSent {
            get {
                return ResourceManager.GetString("PasswordReset.EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password.
        /// </summary>
        public static string PasswordReset_Heading {
            get {
                return ResourceManager.GetString("PasswordReset.Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password reset link has expired or is not valid.
        /// </summary>
        public static string PasswordReset_InvalidToken {
            get {
                return ResourceManager.GetString("PasswordReset.InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was successfully changed.
        /// </summary>
        public static string PasswordReset_Succeeded {
            get {
                return ResourceManager.GetString("PasswordReset.Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select payment method.
        /// </summary>
        public static string Payment_PaymentMethodRequired {
            get {
                return ResourceManager.GetString("Payment.PaymentMethodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How would you like to pay?.
        /// </summary>
        public static string Payment_SelectPayment {
            get {
                return ResourceManager.GetString("Payment.SelectPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Please select).
        /// </summary>
        public static string Payment_SelectPaymentMethod {
            get {
                return ResourceManager.GetString("Payment.SelectPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In stock.
        /// </summary>
        public static string Product_InStock {
            get {
                return ResourceManager.GetString("Product.InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string Product_NotAvailable {
            get {
                return ResourceManager.GetString("Product.NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of stock.
        /// </summary>
        public static string Product_OutOfStock {
            get {
                return ResourceManager.GetString("Product.OutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string Product_Parameters {
            get {
                return ResourceManager.GetString("Product.Parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Product_Price {
            get {
                return ResourceManager.GetString("Product.Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Product_TotalPrice {
            get {
                return ResourceManager.GetString("Product.TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You save.
        /// </summary>
        public static string Product_YouSave {
            get {
                return ResourceManager.GetString("Product.YouSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestseller.
        /// </summary>
        public static string PublicStatus_Bestseller {
            get {
                return ResourceManager.GetString("PublicStatus.Bestseller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On sale.
        /// </summary>
        public static string PublicStatus_OnSale {
            get {
                return ResourceManager.GetString("PublicStatus.OnSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account?.
        /// </summary>
        public static string Register_AlreadyHaveAnAccount {
            get {
                return ResourceManager.GetString("Register.AlreadyHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email (User name).
        /// </summary>
        public static string Register_EmailUserName {
            get {
                return ResourceManager.GetString("Register.EmailUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email.
        /// </summary>
        public static string Register_EmailUserName_Empty {
            get {
                return ResourceManager.GetString("Register.EmailUserName.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Register_FirstName {
            get {
                return ResourceManager.GetString("Register.FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your first name.
        /// </summary>
        public static string Register_FirstName_Empty {
            get {
                return ResourceManager.GetString("Register.FirstName.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Register_LastName {
            get {
                return ResourceManager.GetString("Register.LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your last name.
        /// </summary>
        public static string Register_LastName_Empty {
            get {
                return ResourceManager.GetString("Register.LastName.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your password.
        /// </summary>
        public static string Register_Password {
            get {
                return ResourceManager.GetString("Register.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        public static string Register_Password_Empty {
            get {
                return ResourceManager.GetString("Register.Password.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your password.
        /// </summary>
        public static string Register_PasswordConfirmation {
            get {
                return ResourceManager.GetString("Register.PasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your password.
        /// </summary>
        public static string Register_PasswordConfirmation_Empty {
            get {
                return ResourceManager.GetString("Register.PasswordConfirmation.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match the confirmation password.
        /// </summary>
        public static string Register_PasswordConfirmation_Invalid {
            get {
                return ResourceManager.GetString("Register.PasswordConfirmation.Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create your own account and enjoy smooth shopping experience at Dancing Goat..
        /// </summary>
        public static string Register_Subheading {
            get {
                return ResourceManager.GetString("Register.Subheading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roastery.
        /// </summary>
        public static string Roastery {
            get {
                return ResourceManager.GetString("Roastery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, no results match {0}.
        /// </summary>
        public static string Search_NoResults {
            get {
                return ResourceManager.GetString("Search.NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for &quot;{0}&quot;.
        /// </summary>
        public static string Search_ResultsFor {
            get {
                return ResourceManager.GetString("Search.ResultsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected delivery method is not applicable..
        /// </summary>
        public static string Shipping_NotApplicable {
            get {
                return ResourceManager.GetString("Shipping.NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select delivery method.
        /// </summary>
        public static string Shipping_SelectShipping {
            get {
                return ResourceManager.GetString("Shipping.SelectShipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery method.
        /// </summary>
        public static string Shipping_ShippingOption {
            get {
                return ResourceManager.GetString("Shipping.ShippingOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a delivery method.
        /// </summary>
        public static string Shipping_ShippingOptionRequired {
            get {
                return ResourceManager.GetString("Shipping.ShippingOptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping cart.
        /// </summary>
        public static string ShoppingCart {
            get {
                return ResourceManager.GetString("ShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spend {0} more and get free delivery today!.
        /// </summary>
        public static string ShoppingCart_FreeDelivery {
            get {
                return ResourceManager.GetString("ShoppingCart.FreeDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string ShoppingCart_Remove {
            get {
                return ResourceManager.GetString("ShoppingCart.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        public static string ShoppingCart_Shipping {
            get {
                return ResourceManager.GetString("ShoppingCart.Shipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total (incl. tax estimate).
        /// </summary>
        public static string ShoppingCart_Total {
            get {
                return ResourceManager.GetString("ShoppingCart.Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total tax.
        /// </summary>
        public static string ShoppingCart_TotalTax {
            get {
                return ResourceManager.GetString("ShoppingCart.TotalTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a number greater than 0 to the Units field..
        /// </summary>
        public static string ShoppingCart_UnitsGreaterThanZero {
            get {
                return ResourceManager.GetString("ShoppingCart.UnitsGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update.
        /// </summary>
        public static string ShoppingCart_Update {
            get {
                return ResourceManager.GetString("ShoppingCart.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cart.
        /// </summary>
        public static string ShoppingCart_YourCart {
            get {
                return ResourceManager.GetString("ShoppingCart.YourCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email / User name.
        /// </summary>
        public static string SignIn_EmailUserName {
            get {
                return ResourceManager.GetString("SignIn.EmailUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email / user name.
        /// </summary>
        public static string SignIn_EmailUserName_Empty {
            get {
                return ResourceManager.GetString("SignIn.EmailUserName.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten password.
        /// </summary>
        public static string SignIn_ForgottenPassword {
            get {
                return ResourceManager.GetString("SignIn.ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It only takes a moment to get started..
        /// </summary>
        public static string SignIn_ItOnlyTakesAMoment {
            get {
                return ResourceManager.GetString("SignIn.ItOnlyTakesAMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New to Dancing Goat?.
        /// </summary>
        public static string SignIn_NewToDancingGoat {
            get {
                return ResourceManager.GetString("SignIn.NewToDancingGoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SignIn_Password {
            get {
                return ResourceManager.GetString("SignIn.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay signed in.
        /// </summary>
        public static string SignIn_StaySignedIn {
            get {
                return ResourceManager.GetString("SignIn.StaySignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product catalog.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our story.
        /// </summary>
        public static string Story_Title {
            get {
                return ResourceManager.GetString("Story.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read the whole story.
        /// </summary>
        public static string Story_WholeStory {
            get {
                return ResourceManager.GetString("Story.WholeStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account.
        /// </summary>
        public static string YourAccount {
            get {
                return ResourceManager.GetString("YourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back to Your Account.
        /// </summary>
        public static string YourAccount_Back {
            get {
                return ResourceManager.GetString("YourAccount.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal details.
        /// </summary>
        public static string YourAccount_PersonalDetails {
            get {
                return ResourceManager.GetString("YourAccount.PersonalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string YourAccount_Roles {
            get {
                return ResourceManager.GetString("YourAccount.Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal details save failed.
        /// </summary>
        public static string YourAccount_SaveError {
            get {
                return ResourceManager.GetString("YourAccount.SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update personal details.
        /// </summary>
        public static string YourAccount_Update {
            get {
                return ResourceManager.GetString("YourAccount.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order date.
        /// </summary>
        public static string YourOrders_Date {
            get {
                return ResourceManager.GetString("YourOrders.Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Detail.
        /// </summary>
        public static string YourOrders_OrderDetail {
            get {
                return ResourceManager.GetString("YourOrders.OrderDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back to Your Orders.
        /// </summary>
        public static string YourOrders_OrderDetail_Back {
            get {
                return ResourceManager.GetString("YourOrders.OrderDetail.Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Items.
        /// </summary>
        public static string YourOrders_OrderDetail_Items {
            get {
                return ResourceManager.GetString("YourOrders.OrderDetail.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL (incl. tax):.
        /// </summary>
        public static string YourOrders_OrderDetail_Total {
            get {
                return ResourceManager.GetString("YourOrders.OrderDetail.Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order ID.
        /// </summary>
        public static string YourOrders_OrderId {
            get {
                return ResourceManager.GetString("YourOrders.OrderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your orders.
        /// </summary>
        public static string YourOrders_Orders {
            get {
                return ResourceManager.GetString("YourOrders.Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string YourOrders_Status {
            get {
                return ResourceManager.GetString("YourOrders.Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string YourOrders_Total {
            get {
                return ResourceManager.GetString("YourOrders.Total", resourceCulture);
            }
        }
    }
}
